spring.application.name=astraai

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=

# External APIs URLs & Keys
api.clima.url=https://api.openweathermap.org
api.clima.key=

# OpenFeign Timeout Configurations
# Configure a global timeout of 3000ms (3s) to prevent the ESP32 from hanging
spring.cloud.openfeign.client.config.default.connectTimeout=
spring.cloud.openfeign.client.config.default.readTimeout=