-- Gerado por Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   em:        2026-06-08 20:45:33 BRT
--   site:      Oracle Database 21c
--   tipo:      Oracle Database 21c



DROP TABLE AST_CLIENTE_PREMIUM CASCADE CONSTRAINTS 
;

DROP TABLE AST_HISTORICO_CONEXAO CASCADE CONSTRAINTS 
;

DROP TABLE AST_HISTORICO_DESVIO CASCADE CONSTRAINTS 
;

DROP TABLE AST_LEILAO_BIDDING CASCADE CONSTRAINTS 
;

DROP TABLE AST_LOG_TRANSACAO CASCADE CONSTRAINTS 
;

DROP TABLE AST_RECTENNA CASCADE CONSTRAINTS 
;

DROP TABLE AST_SATELITE CASCADE CONSTRAINTS 
;

DROP SEQUENCE SEQ_AST_CLIENTE 
;

DROP SEQUENCE SEQ_AST_DESVIO 
;

DROP SEQUENCE SEQ_AST_LEILAO 
;

DROP SEQUENCE SEQ_AST_RECTENNA 
;

DROP SEQUENCE SEQ_AST_SATELITE 
;

DROP SEQUENCE SEQ_AST_TRANSACAO 
;

DROP INDEX IDX_RECTENNA_LOCALIZACAO;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE SEQUENCE SEQ_AST_CLIENTE 
    START WITH 1 
    INCREMENT BY 1 
    NOCACHE 
;

CREATE SEQUENCE SEQ_AST_DESVIO 
    START WITH 1 
    INCREMENT BY 1 
    NOCACHE 
;

CREATE SEQUENCE SEQ_AST_LEILAO 
    START WITH 1 
    INCREMENT BY 1 
    NOCACHE 
;

CREATE SEQUENCE SEQ_AST_RECTENNA 
    START WITH 1 
    INCREMENT BY 1 
    NOCACHE 
;

CREATE SEQUENCE SEQ_AST_SATELITE 
    START WITH 1 
    INCREMENT BY 1 
    NOCACHE 
;

CREATE SEQUENCE SEQ_AST_TRANSACAO 
    START WITH 1 
    INCREMENT BY 1 
    NOCACHE 
;

CREATE TABLE AST_CLIENTE_PREMIUM 
    ( 
     ID_CLIENTE             NUMBER  NOT NULL , 
     RAZAO_SOCIAL           VARCHAR2 (100)  NOT NULL , 
     CNPJ                   VARCHAR2 (14)  NOT NULL , 
     DEMANDA_CONTRATADA_GWH NUMBER (5,2) , 
     STATUS_CADASTRO        VARCHAR2 (20)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE AST_CLIENTE_PREMIUM 
    ADD CONSTRAINT CK_CLIENTE_STATUS 
    CHECK (STATUS_CADASTRO IN ('Ativo', 'Inativo')) 
;

ALTER TABLE AST_CLIENTE_PREMIUM 
    ADD CONSTRAINT AST_CLIENTE_PREMIUM_PK PRIMARY KEY ( ID_CLIENTE ) ;

ALTER TABLE AST_CLIENTE_PREMIUM 
    ADD CONSTRAINT UK_CLIENTE_CNPJ UNIQUE ( CNPJ ) ;

CREATE TABLE AST_HISTORICO_CONEXAO 
    ( 
     ID_SATELITE       NUMBER  NOT NULL , 
     ID_RECTENNA       NUMBER  NOT NULL , 
     DATA_HORA_CONEXAO TIMESTAMP  NOT NULL , 
     STATUS_CONEXAO    VARCHAR2 (30) 
    ) 
    LOGGING 
;

ALTER TABLE AST_HISTORICO_CONEXAO 
    ADD CONSTRAINT CK_HISTCON_STATUS 
    CHECK (STATUS_CONEXAO IN ('Desviado por Clima', 'Falha de Alinhamento', 'Transmitindo')) 
;

ALTER TABLE AST_HISTORICO_CONEXAO 
    ADD CONSTRAINT PK_HIST_CONEXAO PRIMARY KEY ( ID_SATELITE, ID_RECTENNA, DATA_HORA_CONEXAO ) ;

CREATE TABLE AST_HISTORICO_DESVIO 
    ( 
     ID_DESVIO           NUMBER  NOT NULL , 
     ID_SATELITE         NUMBER  NOT NULL , 
     ID_RECTENNA_ORIGEM  NUMBER  NOT NULL , 
     ID_RECTENNA_DESTINO NUMBER  NOT NULL , 
     DATA_HORA_MANOBRA   TIMESTAMP  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE AST_HISTORICO_DESVIO 
    ADD CONSTRAINT AST_HISTORICO_DESVIO_PK PRIMARY KEY ( ID_DESVIO ) ;

CREATE TABLE AST_LEILAO_BIDDING 
    ( 
     ID_LEILAO          NUMBER  NOT NULL , 
     ID_SATELITE        NUMBER  NOT NULL , 
     ID_RECTENNA_ORIGEM NUMBER  NOT NULL , 
     DATA_HORA_INICIO   TIMESTAMP  NOT NULL , 
     DATA_HORA_FIM      TIMESTAMP  NOT NULL , 
     GWH_DISPONIVEL     NUMBER (5,2) , 
     PRECO_MIN_POR_GWH  NUMBER (10,2) , 
     STATUS_LEILAO      VARCHAR2 (20)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE AST_LEILAO_BIDDING 
    ADD CONSTRAINT CK_LEILAO_STATUS 
    CHECK (STATUS_LEILAO IN ('Aberto', 'Cancelado', 'Finalizado')) 
;

ALTER TABLE AST_LEILAO_BIDDING 
    ADD CONSTRAINT AST_LEILAO_BIDDING_PK PRIMARY KEY ( ID_LEILAO ) ;

CREATE TABLE AST_LOG_TRANSACAO 
    ( 
     ID_TRANSACAO            NUMBER  NOT NULL , 
     ID_LEILAO               NUMBER  NOT NULL , 
     ID_CLIENTE_VENCEDOR     NUMBER  NOT NULL , 
     VALOR_ARREMATADO        NUMBER (12,2) , 
     TAXA_ORQUESTRACAO_ASTRA NUMBER (10,2) , 
     DATA_FATURAMENTO        DATE  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE AST_LOG_TRANSACAO 
    ADD CONSTRAINT AST_LOG_TRANSACAO_PK PRIMARY KEY ( ID_TRANSACAO ) ;

CREATE TABLE AST_RECTENNA 
    ( 
     ID_RECTENNA              NUMBER  NOT NULL , 
     NOME_SUBESTACAO          VARCHAR2 (50)  NOT NULL , 
     LATITUDE                 NUMBER (10,7)  NOT NULL , 
     LONGITUDE                NUMBER (10,7)  NOT NULL , 
     CAPACIDADE_SUPORTADA_GWH NUMBER (5,2) , 
     STATUS_OPERACIONAL       VARCHAR2 (20)  NOT NULL , 
     LOCALIZACAO              MDSYS.SDO_GEOMETRY 
    ) 
    LOGGING 
;

ALTER TABLE AST_RECTENNA 
    ADD CONSTRAINT CK_RECTENNA_STATUS 
    CHECK (STATUS_OPERACIONAL IN ('Ativa', 'Inativa')) 
;
CREATE INDEX IDX_RECTENNA_LOCALIZACAO ON AST_RECTENNA 
    ( 
     LOCALIZACAO 
    ) 
    INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2 
;

ALTER TABLE AST_RECTENNA 
    ADD CONSTRAINT AST_RECTENNA_PK PRIMARY KEY ( ID_RECTENNA ) ;

CREATE TABLE AST_SATELITE 
    ( 
     ID_SATELITE        NUMBER  NOT NULL , 
     NOME_SATELITE      VARCHAR2 (50)  NOT NULL , 
     STATUS_OPERACIONAL VARCHAR2 (20)  NOT NULL , 
     EFICIENCIA_PAINEIS NUMBER (5,2) , 
     CAPACIDADE_MAX_GW  NUMBER (5,2) 
    ) 
    LOGGING 
;

ALTER TABLE AST_SATELITE 
    ADD CONSTRAINT CK_SAT_STATUS 
    CHECK (STATUS_OPERACIONAL IN ('Ativo', 'Inativo', 'Manutencao')) 
;

ALTER TABLE AST_SATELITE 
    ADD CONSTRAINT AST_SATELITE_PK PRIMARY KEY ( ID_SATELITE ) ;

ALTER TABLE AST_HISTORICO_DESVIO 
    ADD CONSTRAINT FK_DESVIO_DESTINO FOREIGN KEY 
    ( 
     ID_RECTENNA_DESTINO
    ) 
    REFERENCES AST_RECTENNA 
    ( 
     ID_RECTENNA
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE AST_HISTORICO_DESVIO 
    ADD CONSTRAINT FK_DESVIO_ORIGEM FOREIGN KEY 
    ( 
     ID_RECTENNA_ORIGEM
    ) 
    REFERENCES AST_RECTENNA 
    ( 
     ID_RECTENNA
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE AST_HISTORICO_DESVIO 
    ADD CONSTRAINT FK_DESVIO_SAT FOREIGN KEY 
    ( 
     ID_SATELITE
    ) 
    REFERENCES AST_SATELITE 
    ( 
     ID_SATELITE
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE AST_HISTORICO_CONEXAO 
    ADD CONSTRAINT FK_HISTCON_RECT FOREIGN KEY 
    ( 
     ID_RECTENNA
    ) 
    REFERENCES AST_RECTENNA 
    ( 
     ID_RECTENNA
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE AST_HISTORICO_CONEXAO 
    ADD CONSTRAINT FK_HISTCON_SAT FOREIGN KEY 
    ( 
     ID_SATELITE
    ) 
    REFERENCES AST_SATELITE 
    ( 
     ID_SATELITE
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE AST_LEILAO_BIDDING 
    ADD CONSTRAINT FK_LEILAO_RECT FOREIGN KEY 
    ( 
     ID_RECTENNA_ORIGEM
    ) 
    REFERENCES AST_RECTENNA 
    ( 
     ID_RECTENNA
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE AST_LEILAO_BIDDING 
    ADD CONSTRAINT FK_LEILAO_SAT FOREIGN KEY 
    ( 
     ID_SATELITE
    ) 
    REFERENCES AST_SATELITE 
    ( 
     ID_SATELITE
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE AST_LOG_TRANSACAO 
    ADD CONSTRAINT FK_TRANS_CLIENTE FOREIGN KEY 
    ( 
     ID_CLIENTE_VENCEDOR
    ) 
    REFERENCES AST_CLIENTE_PREMIUM 
    ( 
     ID_CLIENTE
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE AST_LOG_TRANSACAO 
    ADD CONSTRAINT FK_TRANS_LEILAO FOREIGN KEY 
    ( 
     ID_LEILAO
    ) 
    REFERENCES AST_LEILAO_BIDDING 
    ( 
     ID_LEILAO
    ) 
    NOT DEFERRABLE 
;

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
)
VALUES (
    'AST_RECTENNA',
    'LOCALIZACAO',
    MDSYS.SDO_DIM_ARRAY(
        MDSYS.SDO_DIM_ELEMENT(
            'LONGITUDE',
            -180,
            180,
            0.005
        ),
        MDSYS.SDO_DIM_ELEMENT(
            'LATITUDE',
            -90,
            90,
            0.005
        )
    ),
    4326
);
COMMIT;


-- Relatório do Resumo do Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             1
-- ALTER TABLE                             22
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          6
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0